function(flotilla_test name)
  add_executable(${name} ${name}.cc)
  target_link_libraries(${name} ${ARGN} GTest::gtest_main)
  gtest_discover_tests(${name})
endfunction()

flotilla_test(common_test flotilla_common)
flotilla_test(wal_test flotilla_storage)
flotilla_test(memtable_test flotilla_storage)
flotilla_test(sstable_test flotilla_storage)
flotilla_test(db_test flotilla_storage)
flotilla_test(net_test flotilla_server flotilla_client)
flotilla_test(raft_storage_test flotilla_raft)
flotilla_test(raft_sim_test flotilla_raft)
